### ISSUE TITLE
Error in LRP module

### ISSUE THREAD

**Issue by arpitmehta22** [SunJiamei/LRP-imagecaptioning-pytorch#1]
Traceback (most recent call last):
  File "/home/arpitmehta/Documents/LRP-imagecaptioning-pytorch-master/models/gridTDmodel.py", line 3108, in <module>
    ExplainGridTDAttention(args, word_map).explain_caption(
  File "/home/arpitmehta/Documents/LRP-imagecaptioning-pytorch-master/models/gridTDmodel.py", line 1447, in explain_caption
    relevance_img = self.explain_cnn(relevance_img_feature)
  File "/home/arpitmehta/Documents/LRP-imagecaptioning-pytorch-master/models/gridTDmodel.py", line 1434, in explain_cnn
    relevance_img = self.model.img_encoder.encoder.compute_lrp(
  File "../LRPtools/lrp_wrapper.py", line 61, in <lambda>
    model.compute_lrp = lambda sample, **kwargs: compute_lrp(
  File "../LRPtools/lrp_wrapper.py", line 86, in compute_lrp
    loss.backward(anchor, retain_graph=True)
  File "/home/arpitmehta/.local/lib/python3.9/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/arpitmehta/.local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
  File "../LRPtools/lrp_wrapper.py", line 19, in lrp_hook
    return lrp_module.propagate_relevance(module, relevance_input,
  File "../LRPtools/lrp_modules.py", line 185, in propagate_relevance
    assert relevance_input[1].shape == module.weight.shape
AssertionError

Kindly help in resolving this issue.

**Comment by SunJiamei** [comment]
This could happen for torch 1.5.0 or higher. The possible reason is the order of the input tensors and output tensors of the gradient auto grad.

Please try torch 1.4.0.
I have updated the Readme for this issue.

Thank you.
